name: Update gas inflation data

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update_data:
    name: Update data with newest gas inflation data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt
 
      - name: Run Script
        run: |
             python gas_destatis.py
      
      - name: Check for changes and commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update gas data
             
      - name: Push Changes
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git push origin main
